#! /usr/bin/env python3
"""aha.py

Web scrape AHA pickup locations.

Usage:
    aha.py <street> <house_number> [options]

Options:
    --help, -h          Print this.page.
"""
from docopt import docopt

from aha import AhaDisposalClient


def main(options):
    """Runs the web scraper."""

    street = options['<street>']
    house_number = options['<house_number>']
    client = AhaDisposalClient()
    pickup_information = client.by_address(street, house_number)
    print(pickup_information)


if __name__ == '__main__':
    main(docopt(__doc__))
